version: '3.5'

services:
  postgres1:
    container_name: postgres_container_1
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mityushkin_216}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mityushkin_216}
      PGDATA: /data/postgres
    volumes:
       - postgres1:/data/postgres
       - ./docker/db/config/1/1.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped
  postgres2:
    container_name: postgres_container_2
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mityushkin_216}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mityushkin_216}
      PGDATA: /data/postgres
    volumes:
       - postgres2:/data/postgres
       - ./docker/db/config/2/2.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped
  postgres3:
    container_name: postgres_container_3
    image: postgres:14.5
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-mityushkin_216}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mityushkin_216}
      PGDATA: /data/postgres
    volumes:
       - postgres3:/data/postgres
       - ./docker/db/config/3/3.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5434:5432"
    networks:
      - postgres
    restart: unless-stopped
networks:
  postgres:
    driver: bridge
volumes:
    postgres1:
    postgres2:
    postgres3:
